### ISSUE TITLE
stack level too deep (SystemStackError)

### ISSUE THREAD

**Issue by atulj** [ruby-prof/ruby-prof#130]
I am using to profile couple of my Ruby programs. In one of the programs, I get the following error when I call RubyProf.stop
ruby-prof-0.13.0/lib/ruby-prof/profile.rb:18: stack level too deep (SystemStackError)

Any solutions / fix for this?

**Comment by ioquatix** [comment]
Okay, so this issue has popped up again on Ruby 2.4.0 and ruby-prof-0.16.2 - odd?

**Comment by rdp** [comment]
Small reproducible test case possible?
