### ISSUE TITLE
app error: No such file or directory @ rb_sysopen - /tmp/profile/

### ISSUE THREAD

**Issue by siva3395** [ruby-prof/ruby-prof#149]
Hi I am facing the error while logging, Could any one please help me..

<pre>
E, [2014-09-05T12:58:31.640115 #8305] ERROR -- : app error: No such file or directory @ rb_sysopen - /tmp/profile/<controller>-<action>-flat.txt (Errno::ENOENT)
E, [2014-09-05T12:58:31.640263 #8305] ERROR -- : /home/<usr>/.rvm/gems/ruby-2.1.2/gems/ruby-prof-0.15.1/lib/ruby-prof/rack.rb:42:in `initialize'
E, [2014-09-05T12:58:31.640312 #8305] ERROR -- : /home/<usr>/.rvm/gems/ruby-2.1.2/gems/ruby-prof-0.15.1/lib/ruby-prof/rack.rb:42:in `open'
E, [2014-09-05T12:58:31.640366 #8305] ERROR -- : /home/<usr>/.rvm/gems/ruby-2.1.2/gems/ruby-prof-0.15.1/lib/ruby-prof/rack.rb:42:in `block in print'
E, [2014-09-05T12:58:31.640418 #8305] ERROR -- : /home/<usr>/.rvm/gems/ruby-2.1.2/gems/ruby-prof-0.15.1/lib/ruby-prof/rack.rb:39:in `each'
E, [2014-09-05T12:58:31.640495 #8305] ERROR -- : /home/<usr>/.rvm/gems/ruby-2.1.2/gems/ruby-prof-0.15.1/lib/ruby-prof/rack.rb:39:in `print'
E, [2014-09-05T12:58:31.640551 #8305] ERROR -- : /home/<usr>/.rvm/gems/ruby-2.1.2/gems/ruby-prof-0.15.1/lib/ruby-prof/rack.rb:33:in `call'
E, [2014-09-05T12:58:31.640602 #8305] ERROR -- : /home/<usr>/.rvm/gems/ruby-2.1.2/gems/rack-1.5.2/lib/rack/content_length.rb:14:in `call'
E, [2014-09-05T12:58:31.640654 #8305] ERROR -- : /home/<usr>/.rvm/gems/ruby-2.1.2/gems/unicorn-4.8.2/lib/unicorn/http_server.rb:572:in `process_client'
E, [2014-09-05T12:58:31.640705 #8305] ERROR -- : /home/<usr>/.rvm/gems/ruby-2.1.2/gems/unicorn-4.8.2/lib/unicorn/http_server.rb:666:in `worker_loop'
E, [2014-09-05T12:58:31.640757 #8305] ERROR -- : /home/<usr>/.rvm/gems/ruby-2.1.2/gems/unicorn-4.8.2/lib/unicorn/http_server.rb:521:in `spawn_missing_workers'
E, [2014-09-05T12:58:31.640809 #8305] ERROR -- : /home/<usr>/.rvm/gems/ruby-2.1.2/gems/unicorn-4.8.2/lib/unicorn/http_server.rb:140:in `start'
E, [2014-09-05T12:58:31.640861 #8305] ERROR -- : /home/<usr>/.rvm/gems/ruby-2.1.2/gems/unicorn-rails-1.1.0/lib/unicorn/rails.rb:24:in `run'
E, [2014-09-05T12:58:31.640912 #8305] ERROR -- : /home/<usr>/.rvm/gems/ruby-2.1.2/gems/rack-1.5.2/lib/rack/server.rb:264:in `start'
E, [2014-09-05T12:58:31.640979 #8305] ERROR -- : /home/<usr>/.rvm/gems/ruby-2.1.2/gems/railties-4.0.3/lib/rails/commands/server.rb:84:in `start'
E, [2014-09-05T12:58:31.641030 #8305] ERROR -- : /home/<usr>/.rvm/gems/ruby-2.1.2/gems/railties-4.0.3/lib/rails/commands.rb:76:in `block in <top (required)>'
E, [2014-09-05T12:58:31.641081 #8305] ERROR -- : /home/<usr>/.rvm/gems/ruby-2.1.2/gems/railties-4.0.3/lib/rails/commands.rb:71:in `tap'
E, [2014-09-05T12:58:31.641133 #8305] ERROR -- : /home/<usr>/.rvm/gems/ruby-2.1.2/gems/railties-4.0.3/lib/rails/commands.rb:71:in `<top (required)>'
E, [2014-09-05T12:58:31.641184 #8305] ERROR -- : bin/rails:4:in `require'
E, [2014-09-05T12:58:31.641234 #8305] ERROR -- : bin/rails:4:in `<main>'
</pre>

**Comment by hitechkaran** [comment]
No platform was selected, choosing Msf::Module::Platform::Android from the payload
No Arch selected, selecting Arch: dalvik from the payload
No encoder or badchars specified, outputting raw payload
Payload size: 8812 bytes
Saved as: /root/TheFatRat/temp/payload.apk
Generating 2,048 bit RSA key pair and self-signed certificate (SHA256withRSA) with a validity of 10,000 days
	for: CN=Android Debug, O=Android, C=US
[Storing /root/TheFatRat/temp/debug.keystore]

**Comment by rdp** [comment]
Is that a ruby_prof issue?

On Friday, October 27, 2017, hitechkaran <notifications@github.com> wrote:
> No platform was selected, choosing Msf::Module::Platform::Android from
the payload
> No Arch selected, selecting Arch: dalvik from the payload
> No encoder or badchars specified, outputting raw payload
> Payload size: 8812 bytes
> Saved as: /root/TheFatRat/temp/payload.apk
> Generating 2,048 bit RSA key pair and self-signed certificate
(SHA256withRSA) with a validity of 10,000 days
> for: CN=Android Debug, O=Android, C=US
> [Storing /root/TheFatRat/temp/debug.keystore]
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci6.googleusercontent.com/proxy/JuE-oroqc_LoSpdQwG-r1e01txtsFnWGAKIXHpOyZTlQ_95VH0htr9XMfb62aRxf8qbJXV0stx75ZMFbU1-A-Cgyrr1G0sCpZqiFfOKnr-E_3i2ytJhg9MOJWCiLT7Xj3s-8T4Z6xjqiw42uhG9WydliSsNSsQ=s0-d-e1-ft#https://github.com/notifications/beacon/AAAw0KOh-p97Yfuvzhz9J8WZUyUTEaKTks5swrfSgaJpZM4Ce2aS.gif>
