### ISSUE TITLE
Calls to dynamically created methods wrongly assigned

### ISSUE THREAD

**Issue by philippm** [ruby-prof/ruby-prof#153]
To reproduce:

```ruby
#!/usr/bin/env ruby
require 'ruby-prof'

RubyProf.start

class FruitMedley
  FRUITS=[:banana, :apple]

  FRUITS.each do |fruit|
    define_method(fruit) do
      "I'm a #{fruit}"
    end
  end
end

printer = FruitMedley.new
100.times { puts printer.banana }
100.times { puts printer.apple }

result = RubyProf.stop
printer = RubyProf::FlatPrinter.new(result)
printer.print(STDOUT)
```

This creates two methods dynamically: `banana` and `apple`. The profiler assigns all calls to either of these methods to the last one defined, in this case `apple`:

    %self      total      self      wait     child     calls  name
    24.40      0.001     0.001     0.000     0.000      200   FruitMedley#apple
                                                        ^^^
    ...

The output shows 200 calls to `apple` and none to `banana`. The correct output would be 100 calls to `apple` and the same to `banana`.

**Comment by skaes** [comment]
thx for the report. we'll have a look.
