### ISSUE TITLE
Can's set measurement

### ISSUE THREAD

**Issue by st0012** [ruby-prof/ruby-prof#156]
I followed the step to set up measurement by export `RUBY_PROF_MEASURE_MODE=memory` in my environment variable, but i still get the process time as result.
And when I bound before the `RubyProf.start` line and get  `"RUBY_PROF_MEASURE_MODE" => "memory"` while the result remain the same.
So I want to ask that if i did something wrong or it needs more configuration to change the measurement?

**Comment by skaes** [comment]
You didn't do anything wrong. It's a bug. fixed in 38d9c5f28d1cd6434052a20d8c20cbfff85f0e62
