### ISSUE TITLE
Memory measurement not working ?

### ISSUE THREAD

**Issue by kushbhandari** [ruby-prof/ruby-prof#166]
I am trying to see memory usage reports by setting <code>RubyProf::MEMORY</code>but in the output I see Total is 0.0000 and %self is <code>NaN</code> for everything. What is wrong here ?

<pre>
Measurement: 4
Thread ID: 70239639518160
Fiber ID: 70239711444080
Total: 0.000000
Sort by: self_time

 %self      total      self      wait     child     calls  name
   NaN      0.000     0.000     0.000     0.000       30   Object#duplicable?
</pre>

This is how I am profiling:

<pre>
RubyProf.start
RubyProf.measure_mode = RubyProf::MEMORY
puts("Measurement: #{RubyProf.measure_mode}")
....code to profile....
result = RubyProf.stop
printer = RubyProf::FlatPrinter.new(result)
printer.print(STDOUT)
</pre>

**Comment by skaes** [comment]
For measuring memory you need a patched ruby: https://github.com/skaes/rvm-patchsets
