### ISSUE TITLE
Call Stack Report - number inside parenthesis

### ISSUE THREAD

**Issue by ayashjorden** [ruby-prof/ruby-prof#167]
Hi,
What is the number inside the parenthesis (A in the example below) and the one inside the square brackets (B in the example below)?

![image](https://cloud.githubusercontent.com/assets/4204371/9489804/54b9f9a6-4bec-11e5-87ff-2095f75e32ab.png)

Thank you,
Yarden

**Comment by skaes** [comment]
The first number is percentage relative to thread, the number inside parentheses is relativ to the parent.

**Comment by ayashjorden** [comment]
@skaes Thank you for the explanation.
I still don't understand the square brackets numbers, can you elaborate?

Thanks again,
Yarden

**Comment by skaes** [comment]
Sorry, I overlooked the second part of the question.

4 calls, 269 total

means that this node represents 4 calls to Redis::Connection#read, but other nodes of the call tree represent 265 calls.

**Comment by ayashjorden** [comment]
Thanks for clarifying that :)
