### ISSUE TITLE
Flat profile doesn't look like example.

### ISSUE THREAD

**Issue by jcoyne** [ruby-prof/ruby-prof#169]
In the example here: https://github.com/ruby-prof/ruby-prof/blob/master/examples/flat.txt
These columns are present:
```
 %self  cumulative  total     self   children  calls self/call total/call  name
 46.34     4.06      8.72     4.06     4.66      501     0.01     0.02     Integer#upto
```

When I run the flat printer I get output like this
https://gist.github.com/jcoyne/34f0bb1f73ef5975b2ca The `self/call` and `total/call` columns are missing.  How do I get those to display?

**Comment by jcoyne** [comment]
It's curious because the FlatPrinter and the sample were added in this commit: https://github.com/ruby-prof/ruby-prof/commit/7ec8a86b248b53f9af14e957909c2f15f8a01fc7  but it doesn't look like that sample matched the code even then.

**Comment by rdp** [comment]
probably just outdated somehow, pull request welcome :)
