### ISSUE TITLE
CallInfo's `recursive` and `non_recursive?` properties

### ISSUE THREAD

**Issue by nelgau** [ruby-prof/ruby-prof#170]
Good day, everyone!

Before I say anything else, please know that `ruby-prof` has proven to be an invaluable performance auditing tool in my work, especially in combination with cachegrind visualization and aggressive method elimination (e.g., removing vertices of simultaneously high in and out degrees). I've also found it easy to extend: just expose a new monotonic performance counter and bang out the measure implementation.

It's a pleasure to explore the call graph of a large Rails app, identify many small targets, then, armed with data, get others excited about knocking these out, and feel the delight of all these little wins adding up to something of great significance. I'm actively exploring duty-cycling the profiler (in short bursts) and emitting small, raw profiles for aggregation—in other words, the spectrum between sampling and tracing.

So, yes! I'm a fan of what you've done. Thank you for all your hard work!

--

Having had such success, naturally, I want to know everything I can about the design. I've spent much time studying the "online" component of the profiler (construction of the `prof_call_info_t` data). I'm only just now getting around to reading the Ruby side of it.

It probably comes as no surprise to you that, above all else, I'm deeply curious about how the recursion properties are computed, exposed to the consumer, and what they signify concretely. The test suite does a good job of demonstrating the intention behind `CallInfo#recursive` by contrasting it with the output of the `#call_sequence` method. This is a great boon in lieu of explicit documentation.

On the other hand, I'm having great difficulty understanding the purpose of `#non_recursive?`. It's not the simple negation of the `recursive` property and, after tracing the flow of data in `#detect_recursion`, I've confused myself even more. As [Feynman says](https://www.youtube.com/watch?v=Uxa1gLt5YKI), this is an unpleasant feeling and I'm doing my best to make it go away. :)

For reference, here's the code:

```ruby
class RubyProf::CallInfo
  def detect_recursion(visited_methods = Hash.new(0))
    @recursive = (visited_methods[target] += 1) > 1
    @non_recursive = true
    children.each do |child|
      @non_recursive = false if child.detect_recursion(visited_methods)
    end
    visited_methods.delete(target) if (visited_methods[target] -= 1) == 0
    return !@non_recursive
  end
end
```

As I understand it, during the post-processing phase, each thread invokes the `#detect_recursion` method on its root callinfos, the set of callinfos with no parent, the roots of distinct trees of profiled call stacks. Knowing this, I know how `#recursive` is computed and why it has the properties asserted in the test suite. For example. consider the `test_simple` case in `recursive_test.rb`:

```ruby
# Method 1: Object#simple
    
call_info = method.call_infos.first
assert_equal('RecursiveTest#test_simple->Object#simple', call_info.call_sequence)
assert(!call_info.recursive)

call_info = method.call_infos.last
assert_equal('RecursiveTest#test_simple->Object#simple->Object#simple', call_info.call_sequence)
assert(call_info.recursive)
```

Stripping away everything but the paired assertions, this makes perfect sense!

```ruby
'RecursiveTest#test_simple->Object#simple'                 # recursive == false
'RecursiveTest#test_simple->Object#simple->Object#simple'  # recursive == true
```

I can even take a stab at a definition:

> _"A `CallInfo` is recursive iff it is a descendent of a `CallInfo` with the same target."_

What about `#non_recursive?` Is there an intuitive definition for that too? The code suggests:

> _"A `CallInfo` is non-recursive iff all of its descendants are also 'non-recursive.'"_

Of course, this definition is inductive and it works for any node in the graph. Whether the callinfo is a root, an interior node, or a leaf, its `non_recursive?` state is completely determined by the `non_recursive?` states of its children (or lack there of), propagated by the return value of `#detect_recursion`. It appears  the power to affect the outcome is concentrated in the leaf nodes...

But... as leaf nodes, by definition, they have no children, when they receive `#detect_recursion`, they dutifully assert their non-recursiveness by assigning `true` to `@non_recursive` after which they immediately return false. This causes their parents to return false as well, and so on, and so on... until the entire tree computes that every node has `non_recursive? == true`. Even if a few leaves had `@non_recursive` set to `false` _before_ the depth-first search began, that would be wiped out as soon as the method begins execution by the assignment of `true` to `@non_recursive`.

I must be missing something fairly obvious. Otherwise, `non-recursive?` is trivially true but it might be that way by design... you know, like a planned feature (not yet ready for prime time), vestigial code, or a genuine bug. I _do_ see references to it elsewhere though, in the `MethodInfo` model and the GraphPrinter subclasses, so I can hardly assume that it's just dead code.

What did I miss? ;)

**Comment by skaes** [comment]
Thx a lot for the detailed analysis. You haven't missed anything: you have detected a bug.

The non_recursive attribute was meant to speed up recalculation of recursiveness after the first initial pass over the graph. Recalculation is necessary if there are multiple roots for a given thread.

However, I now think this was misguided optimisation attempt which doesn't work in all cases.

I nee to rethink this.

**Comment by skaes** [comment]
For reference: the faulty code is related to fixing issue #136

**Comment by skaes** [comment]
I have fixed the bug. What's still missing though, is to verify whether the new algorithm is still usable.
