### ISSUE TITLE
Document lack of rubinius/rbx and jruby support

### ISSUE THREAD

**Issue by lamont-granquist** [ruby-prof/ruby-prof#174]
Searching for rubinius/rbx didn't turn up anything.  Finally found the statement that this was MRI only under a closed issue for jruby.

Should probably just add that statement to the README.md so its easy to find/search.

**Comment by skaes** [comment]
I don't know where you searched but the github project title says: "ruby-prof: a code profiler for MRI rubies".

Have you actually tried installing the gem under rubinius or jruby?
