### ISSUE TITLE
CPU time should deal with out-of-order instructions

### ISSUE THREAD

**Issue by nateberkopec** [ruby-prof/ruby-prof#181]
> Starting with the Pentium Pro, Intel processors have supported out-of-order execution, where instructions are not necessarily performed in the order they appear in the executable. This can cause RDTSC to be executed later than expected, producing a misleading cycle count.[4] This problem can be solved by executing a serializing instruction, such as CPUID, to force every preceding instruction to complete before allowing the program to continue, or by using the RDTSCP instruction, which is a serializing variant of the RDTSC instruction.

It looks like the current implementation just calls RDTSC alone. [Here's a bit on the tradeoffs between the two approaches.](http://stackoverflow.com/questions/27693145/rdtscp-versus-rdtsc-cpuid)

**Comment by skaes** [comment]
I'm not sure this is a real problem. I suspect the number of instructions executed by the ruby interpreter between two ruby-prof measurement points is high enough so that reordering of instructions on the processor level doesn't affect the accuracy of ruby-prof significantly. Do you have proof to the contrary?

**Comment by nateberkopec** [comment]
Good point, I didn't take into account that we're talking about numbers of instructions *between* ruby events. I don't have any proof of to what degree this affects ruby-prof, and cannot write a test for it because I can't write C :laughing:

**Comment by steakknife** [comment]
For reference, there's the [absolute_time](https://github.com/bwbuchanan/absolute_time/) gem w/ a [native C extension](https://github.com/bwbuchanan/absolute_time/blob/master/ext/absolute_time.c) supporting high-precision wall-time on multiple platforms w/ a `Benchmark` compatible API. Might weigh depending on it, unless all timing has to be done in C.

Having written native extensions for other platforms, [CPython](https://hg.python.org/cpython/file/tip/Modules/timemodule.c) is also a good source of inspiration (don't plagiarize, of course) for common tasks.

**Comment by skaes** [comment]
I really don't have time to work on this, as it seems quite a lot of research would be required and it seems tricky to get right. So it's simply not in my budget.

**Comment by rdp** [comment]
seems to me like RDTSC is going to be "really close to accurate" if it isn't always.  Pull requests always welcome of course. Cheers!
