### ISSUE TITLE
Note that resume will automatically call start if a profiling run has not yet started?

### ISSUE THREAD

**Issue by ioquatix** [ruby-prof/ruby-prof#185]
This is stated in the documentation but I get the following error:

```
     Failure/Error: RubyProf.resume
     
     RuntimeError:
       RubyProf.start was not yet called
```

What am I doing wrong?

**Comment by dgynn** [comment]
The docs are incorrect. You must call `RubyProf.start` first if you want to use `resume`.

**Comment by skaes** [comment]
Fixed documentation in https://github.com/ruby-prof/ruby-prof/commit/4270c15a5fc25b54ec0361b8addcdb171f1e7b39
