### ISSUE TITLE
Segfault error with graph_html_printer

### ISSUE THREAD

**Issue by ASnow** [ruby-prof/ruby-prof#193]
Here the console output:

https://gist.github.com/ASnow/60ffe89d8d3f4788ba8f28eacd57ca97

**Comment by skaes** [comment]
Thx for the report. I'd love to help, but even though you posted a lot of information, and even if I had the program to do debugging, I don't have the time.

It might even be a ruby interpreter bug. The version you use, 2.2.1 is rather old. Could you please try to reproduce the problem using 2.2.5 or 2.3.1?

**Comment by skaes** [comment]
closed because reporter did not respond.
