### ISSUE TITLE
Typo in examples?

### ISSUE THREAD

**Issue by gerrywastaken** [ruby-prof/ruby-prof#196]
> **Object#is_prime** was called 1001 times and 1000 of those calls were made
by **Object#is_prime**.

https://github.com/ruby-prof/ruby-prof/blob/master/examples/graph.txt

Should that say:

> **Integer#upto** was called 1001 times and 1000 of those calls were made
by Object#is_prime.`

or am I misunderstanding the explanation?

**Comment by skaes** [comment]
You are right, the explanation is wrong.

**Comment by gerrywastaken** [comment]
Thanks for the fix.
