### ISSUE TITLE
ActiveRecord Model names are too long

### ISSUE THREAD

**Issue by delwaterman** [ruby-prof/ruby-prof#204]
When dealing with ActiveRecord objects whose name is super long output becomes unreadable. Is it possible to override these or provide a hook to change the display of the name.

![screen shot 2016-10-04 at 4 59 30 pm](https://cloud.githubusercontent.com/assets/70605/19092302/10721754-8a54-11e6-8342-fdf9afa53a03.png)

**Comment by steakknife** [comment]
Should use [`awesome_print`](https://github.com/awesome-print/awesome_print) or something

**Comment by skaes** [comment]
You can override the output formatting by monkey patching ActiveRecord#inspect (or maybe #to_s, I don't know). This is not a ruby-prof problem per se.
