### ISSUE TITLE
Feature Request: Support for dot files in the task library

### ISSUE THREAD

**Issue by khalilfazal** [ruby-prof/ruby-prof#207]
Ruby-prof supports printing a graph profile as a dot file, however the task library currently doesn't support this (version 0.16.2).

See this comment from task.rb:26

    #   printer - Specifies the output printer.  Valid values include
    #             :flat, :graph, :graph_html and :call_tree.

and case block from task.rb:95

    case @printer
      when :flat, :graph, :call_tree
        file_name += ".txt"
      when :graph_html
        file_name += ".html"
      else
        file_name += ".txt"
    end

**Comment by skaes** [comment]
I wan't even aware of task.rb. I'm happy to accept a pull request with a test case.

**Comment by skaes** [comment]
Closing this in appreciation of a future pull request.
