### ISSUE TITLE
Will it shows total blocks/heap lost

### ISSUE THREAD

**Issue by rahulroot** [ruby-prof/ruby-prof#208]
Hello,

I am running this on my ruby daemon, but I don't see any information from profile log, which tell me OK, this much memory you have lost...

Do you have any idea...how to do that...which shows these kinds of information.

BR,
Rahul.

**Comment by rdp** [comment]
If you're talking about honest memory leaks, ruby-prof wouldn't do it,
maybe valgrind?

**Comment by rahulroot** [comment]
I rebuilt the ruby with valgrind options, with -O0 and -g CFLAGS, i ran a sample program with it having loop of 10 items only, It gives me 256MB memory leak...I couldn't believe my eyes...what is happening...

Could you suggest any tools which gives me exact memleak details....just like valgrind do it with c/c++ programs.

I tried to use memory_profiler, but it gives retained and allocated, but it doesn't give information about which is potential leak...

I tried to use GC, objspace, but it gives total no of objects, and I might get info about where are these objects, but it doesn't give information where is the actual accumulation...

I will look more and if possible I will try to do some monkey patching if needed...

Any suggestions is welcome :-)

BR,
Rahul.

**Comment by rdp** [comment]
what's the valgrind output?

**Comment by rahulroot** [comment]
Hello,

ruby -v
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]






This is program.

#!/usr/bin/env ruby

arr = Array.new
v = 1
10000.times {
  arr.push(v)
}
arr = nil

Here is the command which I use for valgrind.
valgrind --tool=memcheck --max-stackframe=8380928 --show-reachable=yes ruby leak.rb

This is what I got.

valgrind --tool=memcheck --max-stackframe=8380928 --show-reachable=yes ruby leak.rb
==22825== Memcheck, a memory error detector
==22825== Copyright (C) 2002-2015, and GNU GPL'd, by Julian Seward et al.
==22825== Using Valgrind-3.12.0 and LibVEX; rerun with -h for copyright info
==22825== Command: ruby leak.rb
==22825==
==22825==
==22825== HEAP SUMMARY:
==22825==     in use at exit: 3,041,589 bytes in 25,732 blocks
==22825==   total heap usage: 51,798 allocs, 26,066 frees, 10,077,145 bytes allocated
==22825==
==22825== LEAK SUMMARY:
==22825==    definitely lost: 504,698 bytes in 4,660 blocks
==22825==    indirectly lost: 563,805 bytes in 7,363 blocks
==22825==      possibly lost: 1,671,060 bytes in 9,575 blocks
==22825==    still reachable: 302,026 bytes in 4,134 blocks
==22825==         suppressed: 0 bytes in 0 blocks
==22825== Rerun with --leak-check=full to see details of leaked memory
==22825==
==22825== For counts of detected and suppressed errors, rerun with: -v
==22825== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 2 from 2)

If you need output with --leak-check=full, let me try if I could attach that log.

**Comment by rahulroot** [comment]
This is ruby version I am using..
ruby -v
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]

uname -a
Linux sles11 3.0.76-0.11-default #1 SMP Fri Jun 14 08:21:43 UTC 2013 (ccab990) x86_64 x86_64 x86_64 GNU/Linux

This is my program.

#!/usr/bin/env ruby

arr = Array.new
v = 1
10000.times {
  arr.push(v)
}
arr = nil


 valgrind --tool=memcheck  --max-stackframe=8380944 --show-reachable=yes ruby leak.rb
==22978== Memcheck, a memory error detector
==22978== Copyright (C) 2002-2015, and GNU GPL'd, by Julian Seward et al.
==22978== Using Valgrind-3.12.0 and LibVEX; rerun with -h for copyright info
==22978== Command: ruby leak.rb
==22978==
==22978==
==22978== HEAP SUMMARY:
==22978==     in use at exit: 3,041,579 bytes in 25,732 blocks
==22978==   total heap usage: 51,798 allocs, 26,066 frees, 10,077,135 bytes allocated
==22978==
==22978== LEAK SUMMARY:
==22978==    definitely lost: 504,698 bytes in 4,660 blocks
==22978==    indirectly lost: 563,795 bytes in 7,363 blocks
==22978==      possibly lost: 1,671,060 bytes in 9,575 blocks
==22978==    still reachable: 302,026 bytes in 4,134 blocks
==22978==         suppressed: 0 bytes in 0 blocks
==22978== Rerun with --leak-check=full to see details of leaked memory
==22978==
==22978== For counts of detected and suppressed errors, rerun with: -v
==22978== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 2 from 2)

I will try add output with leak-check full settings.

**Comment by skaes** [comment]
ruby-prof is not a memory leak detector. Thus, this is not a ruby-prof issue.

Besides, the valgrind output you present is probably misleading, because you're just measuring how much memory isn't freed on program exit. But this doesn't prove there's a memory leak.
