### ISSUE TITLE
CallTreePrinter fails to print to a file

### ISSUE THREAD

**Issue by id4coding** [ruby-prof/ruby-prof#210]
I am trying to profile my ruby code using ruby-prof's call tree printer. I plan to use WinCacheGrind to view the call tree graph. I use IRB 2.3.0 and ruby-prof 0.16.2. Here's my sample test case:  

    require 'ruby-prof' 
    def main
      result = RubyProf.profile do 
        arr = [0,1,2,3,4,5,6,7,8,9]
        arr.each do |i|
          puts i
        end
      end

      printer = RubyProf::CallTreePrinter.new(result)
      File.open("output.out", "w+") { |file| printer.print(file) }
    end

    main

The above code produces a fault. I've named the above file as profiler.rb. I run the above code using "irb profiler.rb". The output of the above program is:

    0
    1
    2
    3
    4
    5
    6
    7
    8
    9
    NoMethodError: undefined method `[]' for #<File:output.out (closed)>
            from /usr/local/lib/ruby/gems/2.3.0/gems/ruby-prof-0.16.2/lib/ruby-prof/printers/call_tree_printer.rb:83:in `base_name' 
            from /usr/local/lib/ruby/gems/2.3.0/gems/ruby-prof-0.16.2/lib/ruby-prof/printers/call_tree_printer.rb:87:in `remove_subsidiary_files_from_previous_profile_runs'
            from /usr/local/lib/ruby/gems/2.3.0/gems/ruby-prof-0.16.2/lib/ruby-prof/printers/call_tree_printer.rb:53:in `print_threads'
            from /usr/local/lib/ruby/gems/2.3.0/gems/ruby-prof-0.16.2/lib/ruby-prof/printers/call_tree_printer.rb:49:in `print'
            from profiler.rb:12:in `block in main'
            from profiler.rb:12:in `open'
            from profiler.rb:12:in `main'
            from profiler.rb:15
            from /usr/local/bin/irb:11:in `<main>'
    profiler.rb(main):016:0>

I searched extensively on Google and found no pointers to resolve the above fault. Any pointers to resolve this will immensely help. Thanks in advance.

**Comment by skaes** [comment]
CallTreePrinter#print does not take an IO object. It behaves like MultiPrinter in this regard. I added some parameter verification to produce better error messages in my last commit 236afa5acc43c0472d216fafecbf970067160c1e.
