### ISSUE TITLE
Storing raw results before printing?

### ISSUE THREAD

**Issue by januszm** [ruby-prof/ruby-prof#211]
Assuming that a developer would like to store results of profiling in a file(s) for later, for use with multiple printers, what would be the recommended way of doing so? I've just tried with `Marshal.dump` but it looks like `RubyProf::Profile` class is missing `_dump_data` method.

If it's possible at all we could add this information to the README file.

**Comment by skaes** [comment]
Great idea, but I don't have time to implement this. Pull requests welcome.
