### ISSUE TITLE
Please, release a new version

### ISSUE THREAD

**Issue by matkoniecz** [ruby-prof/ruby-prof#213]
Currently latest version is 16.2 from 2016-08-25. (according to https://rubygems.org/gems/ruby-prof/)

>  0.16.2 - August 25, 2016 (466 KB) 

It means that crash bug, fixed from october 2016 (https://github.com/ruby-prof/ruby-prof/commit/837edf447914663d0100e5599ab8c44f81f0eae0) is not released.

Please, release a new version.

**Comment by skaes** [comment]
This might take a while. We have recently added rather complex changes to the code base, which I'd prefer to test a bit longer.

In the meantime, I suggest using bundler for your application. It would allow you to refer to the master branch on github (see http://bundler.io/v1.15/git.html).

**Comment by skaes** [comment]
Release 0.17.0
