### ISSUE TITLE
call_tree result in `Not a directory @ rb_sysopen - ruby_prof/profile.callgrind.out.24426 (Errno::ENOTDIR)`

### ISSUE THREAD

**Issue by matkoniecz** [ruby-prof/ruby-prof#215]
To reproduce: 
- clone git repository (at https://github.com/ruby-prof/ruby-prof/commit/3ceadab1440746e1b24c66272f2340a6bc9a99aa)
- modify version number at https://github.com/ruby-prof/ruby-prof/blob/master/lib/ruby-prof/version.rb to 0.16.2.1
- `gem build ruby-prof.gemspec`
- `sudo gem install ruby-prof-0.16.2.1.gem`
- create empty file `empty.rb`
- run `ruby-prof -p call_tree -f ruby_prof empty.rb`

```
/var/lib/gems/2.3.0/gems/ruby-prof-0.16.2.1/lib/ruby-prof/printers/call_tree_printer.rb:79:in `initialize': Not a directory @ rb_sysopen - ruby_prof/profile.callgrind.out.24426 (Errno::ENOTDIR)
	from /var/lib/gems/2.3.0/gems/ruby-prof-0.16.2.1/lib/ruby-prof/printers/call_tree_printer.rb:79:in `open'
	from /var/lib/gems/2.3.0/gems/ruby-prof-0.16.2.1/lib/ruby-prof/printers/call_tree_printer.rb:79:in `print_thread'
	from /var/lib/gems/2.3.0/gems/ruby-prof-0.16.2.1/lib/ruby-prof/printers/call_tree_printer.rb:66:in `block in print_threads'
	from /var/lib/gems/2.3.0/gems/ruby-prof-0.16.2.1/lib/ruby-prof/printers/call_tree_printer.rb:65:in `each'
	from /var/lib/gems/2.3.0/gems/ruby-prof-0.16.2.1/lib/ruby-prof/printers/call_tree_printer.rb:65:in `print_threads'
	from /var/lib/gems/2.3.0/gems/ruby-prof-0.16.2.1/lib/ruby-prof/printers/call_tree_printer.rb:50:in `print'
	from /var/lib/gems/2.3.0/gems/ruby-prof-0.16.2.1/bin/ruby-prof:326:in `block (2 levels) in <top (required)>'
	from /var/lib/gems/2.3.0/gems/ruby-prof-0.16.2.1/bin/ruby-prof:324:in `chdir'
	from /var/lib/gems/2.3.0/gems/ruby-prof-0.16.2.1/bin/ruby-prof:324:in `block in <top (required)>'

```

**Comment by skaes** [comment]
Thx for the report. First question: does the same error happen with earlier versions too?

**Comment by matkoniecz** [comment]
In 0.16.2 `ruby-prof -p call_stack empty.rb` is not crashing.

**Comment by matkoniecz** [comment]
In 0.16.2 it crashes due to #203

> ruby-prof -p call_tree empty.rb
> /home/mateusz/.gem/ruby/2.3.0/gems/ruby-prof-0.16.2/lib/ruby-prof/printers/call_tree_printer.rb:46:in `print': wrong number of arguments (given 2, expected 0..1) (ArgumentError)
>	from /home/mateusz/.gem/ruby/2.3.0/gems/ruby-prof-0.16.2/bin/ruby-prof:335:in `block in <top (required)>'

**Comment by skaes** [comment]
It crashes because call_tree_printer needs a directory. Better error message will given when using latest master.

**Comment by skaes** [comment]
And as stated in #203: this is intentional.

**Comment by matkoniecz** [comment]
Thanks!

**Comment by rdp** [comment]
Stefan for president! :)
