### ISSUE TITLE
Is it possible to tell if the code is currently being profiled or not?

### ISSUE THREAD

**Issue by ioquatix** [ruby-prof/ruby-prof#217]
I'm writing a spec and I'd like to ensure that the spec is running within a profile. Is this possible? e.g. `RubyProf::Profile.current?` or something similar.

**Comment by skaes** [comment]
That is currently not possible. It could possibly be implemented, but I don't feel the use case justifies the extra complexity.

The way ruby-prof knows it needs to measure some piece of code is through ruby's event callbacks. The callback has attached to it the profile instance into which measurements are stored. Newly spawned threads inherit the event callback from their parent (if it has one enabled).

One could, potentially, create a mapping from thread ids to ruby-prof profile instances, but this mapping could become really big and the management of it (adding/removing threads) could be come costly in terms of CPU usage.

**Comment by ioquatix** [comment]
Is it possible to check if the callback is activated for the current thread?

**Comment by skaes** [comment]
@ioquatix I don't think that's possible.

**Comment by skaes** [comment]
@ioquatix I'm curious: why do you need to ensure the spec is run under the profiler? I would consider this part of the test setup and outside the scope of an individual spec.

**Comment by ioquatix** [comment]
I'm writing a spec for a shared context that includes profiling and I want to verify profiling is switched on within the spec.

**Comment by skaes** [comment]
This a rather esoteric use case, I don't intend to support it.

**Comment by ioquatix** [comment]
Thanks for following up.
