### ISSUE TITLE
Module elimination

### ISSUE THREAD

**Issue by der-flo** [ruby-prof/ruby-prof#219]
#202 (method elimination inside the C extension) is a very interesting feature, but it doesn't fit my use-case. I want to profile e. g. RSpec tests. Of course I'm primarily interested in the performance of my code, not the code inside of utilising libraries. So I have to exclude RSpec, VCR, ActiveRecord, ... . This is possible with the following approach:

```ruby
[
  RSpec::Core::Runner,
  RSpec::Core::ExampleGroup,
  RSpec::Core::Hooks::HookCollections,
  RSpec::Core::Example::Procsy,
  RSpec::Core::Hooks::AroundHook,
  RSpec::Core::Configuration,
  RSpec::Core::Example,
  RSpec::Core::Hooks::BeforeHook,
  <...>
].each do |clz|
  profile.exclude_methods! clz, clz.instance_methods
  profile.exclude_methods! clz, clz.private_instance_methods
  profile.exclude_singleton_methods! clz, clz.methods
end
```
But this has 2 major drawbacks: First I have to list many, also private classes, and second it affects performance dramatically. Sure, code like this generates many, many exclusion rules.

The legacy way to eliminate methods using regexes allows excluding complete modules/namespaces, so the rules get reduced to an acceptable minimum. But, as we all know, this approach has the drawback to profile massive amounts of data and filters afterwards, slows us down again.

What about adding the ability to exclude modules with all its methods? This should not affect the performance. Or going a step further and extending this concept to namespaces /  parent modules?

**Comment by skaes** [comment]
Excluding a complete namespace sounds like an interesting feature to me. But I don't think matching on module names or traversing instance hierarchies would be fast enough, so we'd probably would need to enter all the relevant names into the lookup table for excluded methods.

**Comment by skaes** [comment]
@der-flo For the time being, you can simply eliminate the unwanted methods after profiling. Or use the following hack:

```ruby
def exclude_module(profile, mod)
  ObjectSpace.each_object(Module) do |m|
    next unless m.name =~ /\A#{mod}(:?::.*)?\z/
    profile.exclude_methods! m, m.instance_methods
    profile.exclude_methods! m, m.private_instance_methods
    profile.exclude_singleton_methods! m, m.methods
  end
end

```

**Comment by der-flo** [comment]
@skaes Thank your for your suggestion. I played around a bit and it seems quite useful!
Furthermore I don't see the extreme performance affectation anymore. I can't explain that yet.

One shortcoming of `ObjectSpace.each_object(Module) ...` is that it obviously only iterates over the currently loaded modules. In eg. a Rails environment many modules are typically autoloaded, so I cannot exclude them with this strategy. I have to require them manuallly, what makes the maintenance of such a list quite complicated.

I'll dig deeper in this topic they next days. However a native implementation of module exclusion would absolutly make sense, but I understand that this requirement is not trivial.

**Comment by skaes** [comment]
@der-flo you can just eager load the rails app to mitigate the problem. Also, you can add a catch all elimination call for the modules which have not been called:
```ruby
 result.eliminate_methods!([/\A#{mod}(:?::.*)?\z/])
```
This is then slightly less efficient than eliminating them during the profile run, but hey, it works.

**Comment by skaes** [comment]
@schleyfox what's your take on this?

**Comment by skaes** [comment]
@schleyfox any comments on this?

**Comment by schleyfox** [comment]
I think @skaes suggestion to use the legacy method elimination is your best bet given your requirements.  Native method exclusion has a performance advantage because it's only a lookup on a method table keyed by `(class pointer, method id)`.  If we don't have a class to have a pointer to, we're stuck in the land of strings.

Is the performance impact from your first attempt the result of creating all the exclusion rules or felt while running the profile (e.g. is this making the method table lookup less efficient in your experience)?

It's also worth considering that as you eliminate methods (or modules), you lose context and the ability to explain why the performance is the way it is.  Especially if you are lazy loading the rails app while profiling, many methods will be slow because they are finding constants, rather than for any other reason.  Selecting the appropriate visualization can often help with interpretation without hiding the details or framework code.

**Comment by cfis** [comment]
Going to close this, reopen if needed.

**Comment by dmolesUC** [comment]
@cfis I note `eliminate_methods!` is [deprecated](https://github.com/ruby-prof/ruby-prof/blob/v0.17.0/lib/ruby-prof/profile/legacy_method_elimination.rb#L7-L10) in 0.17.0 and gone on `master`. Is there another recommended approach now for this use case?
