### ISSUE TITLE
Filter by single method?

### ISSUE THREAD

**Issue by oswaldoferreira** [ruby-prof/ruby-prof#222]
Would be nice if one could filter _stack traces_ of the final report by a single method, for example:

Let's say I have a class `Ability` with the `allowed?` class method. It may be called by different methods and appear in different levels of the stack result (final profiling result).

But once the final result is normally noisy, it's harder to see how much time is spent in this particular method. 

Does that make sense?

**Comment by skaes** [comment]
If I understand correctly, you want overall time spent in one method. I suggest to use a printer which shows only aggregated results, such as the GraphHtmlPrinter.

If this is not what yo want, please explain.
