### ISSUE TITLE
profiling rails fail

### ISSUE THREAD

**Issue by denglitong** [ruby-prof/ruby-prof#223]
I do as the guide, and start my rails with: ./bin/rails server -b 0.0.0.0 -p 2999 -e profile
when I request the server I get follows : 
[root@SZX1000356499 profiler]# ./bin/rails server -b 0.0.0.0 -p 2999 -e profile
=> Booting Puma
=> Rails 5.1.4 application starting in profile 
=> Run `rails server -h` for more startup options
Puma starting in single mode...
* Version 3.10.0 (ruby 2.4.0-p0), codename: Russell's Teapot
* Min threads: 5, max threads: 5
* Environment: profile
* Listening on tcp://0.0.0.0:2999
Use Ctrl-C to stop
2017-09-30 12:14:15 +0800: Read error: #<NoMethodError: undefined method `each' for nil:NilClass>
/opt/codehub/ruby/lib/ruby/gems/2.4.0/gems/puma-3.10.0/lib/puma/server.rb:682:in `handle_request'
/opt/codehub/ruby/lib/ruby/gems/2.4.0/gems/puma-3.10.0/lib/puma/server.rb:437:in `process_client'
/opt/codehub/ruby/lib/ruby/gems/2.4.0/gems/puma-3.10.0/lib/puma/server.rb:301:in `block in run'
/opt/codehub/ruby/lib/ruby/gems/2.4.0/gems/puma-3.10.0/lib/puma/thread_pool.rb:120:in `block in spawn_thread'

And the profiling files are as follows :
[root@SZX1000356499 profile]# pwd
/tmp/profile
[root@SZX1000356499 profile]# ll
total 176
-rw-r----- 1 root root  25837 Sep 30 12:14 -call_stack.html
-rw-r----- 1 root root   3206 Sep 30 12:14 -flat.txt
-rw-r----- 1 root root 118180 Sep 30 12:14 -graph.html
-rw-r----- 1 root root  23164 Sep 30 12:14 -graph.txt
[root@SZX1000356499 profile]# 

when i change cmd to start server as : `./bin/rails server -b 0.0.0.0 -p 2999 `, which start with deployment mode, then it runs well, so what's problem, how to fix it? thanks much!

**Comment by rdp** [comment]
Works ok without Ruby proof?

On Friday, September 29, 2017, 邓礼桐 <notifications@github.com> wrote:
> I do as the guide, and start my rails with: ./bin/rails server -b 0.0.0.0
-p 2999 -e profile
> when I request the server I get follows :
> [root@SZX1000356499 profiler]# ./bin/rails server -b 0.0.0.0 -p 2999 -e
profile
> => Booting Puma
> => Rails 5.1.4 application starting in profile
> => Run rails server -h for more startup options
> Puma starting in single mode...
>
> Version 3.10.0 (ruby 2.4.0-p0), codename: Russell's Teapot
> Min threads: 5, max threads: 5
> Environment: profile
> Listening on tcp://0.0.0.0:2999
> Use Ctrl-C to stop
> 2017-09-30 12:14:15 +0800: Read error: #<NoMethodError: undefined method
each' for nil:NilClass>
/opt/codehub/ruby/lib/ruby/gems/2.4.0/gems/puma-3.10.0/lib/puma/server.rb:682:inhandle_request'
>
/opt/codehub/ruby/lib/ruby/gems/2.4.0/gems/puma-3.10.0/lib/puma/server.rb:437:in
process_client'
/opt/codehub/ruby/lib/ruby/gems/2.4.0/gems/puma-3.10.0/lib/puma/server.rb:301:inblock
in run'
>
/opt/codehub/ruby/lib/ruby/gems/2.4.0/gems/puma-3.10.0/lib/puma/thread_pool.rb:120:in
`block in spawn_thread'
>
> And the profiling files are as follows :
> [root@SZX1000356499 profile]# pwd
> /tmp/profile
> [root@SZX1000356499 profile]# ll
> total 176
> -rw-r----- 1 root root 25837 Sep 30 12:14 -call_stack.html
> -rw-r----- 1 root root 3206 Sep 30 12:14 -flat.txt
> -rw-r----- 1 root root 118180 Sep 30 12:14 -graph.html
> -rw-r----- 1 root root 23164 Sep 30 12:14 -graph.txt
> [root@SZX1000356499 profile]#
>
> when i change cmd to start server as : ./bin/rails server -b 0.0.0.0 -p
2999, which start with deployment mode, then it runs well, so what's
problem, how to fix it? thanks much!
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci5.googleusercontent.com/proxy/p03mRQAC2tCGDk0BeYvKYWpyG-5lTUTGHMLYsxO-Eog-WJFowXN5Gxn9mOfMQUw66tSKrd5fNEfQY9JTrpqUNPEgjTMZAw1V1I112syfnUk-kLY0wURw2tLkEirhl4-4jccVQsJTcF4nHuzeLhmrQrsr6kYJcA=s0-d-e1-ft#https://github.com/notifications/beacon/AAAw0BltCjLLTkhjI-AC7ZgLQlFP2dBQks5sncE-gaJpZM4PpbyJ.gif>

**Comment by cfis** [comment]
Hmm, going to close this. Reopen if needed.

**Comment by NeilSlater-Clixifix** [comment]
I seem to be getting a very similar issue intermittently, when using `Rack::RubyProf` middleware.

Sometimes the server responds correctly, and I get profiles. Other times I get an error from the default controller, with following stack trace:

```
undefined method `each' for nil:NilClass
Extracted source (around line #447):
445        super()
446        @names = {}
447        hash.each { |k, v| self[k] = v }
448      end
449
450      # on dup/clone, we need to duplicate @names hash
              
Rails.root: /workdir

Application Trace | Framework Trace | Full Trace
rack (2.2.9) lib/rack/utils.rb:447:in `initialize'
rack (2.2.9) lib/rack/utils.rb:440:in `new'
rack (2.2.9) lib/rack/utils.rb:440:in `[]'
rack (2.2.9) lib/rack/etag.rb:29:in `call'
rack (2.2.9) lib/rack/conditional_get.rb:27:in `call'
rack (2.2.9) lib/rack/head.rb:12:in `call'
actionpack (6.0.5.1) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
rack (2.2.9) lib/rack/session/abstract/id.rb:266:in `context'
rack (2.2.9) lib/rack/session/abstract/id.rb:260:in `call'
actionpack (6.0.5.1) lib/action_dispatch/middleware/cookies.rb:654:in `call'
activerecord (6.0.5.1) lib/active_record/migration.rb:567:in `call'
actionpack (6.0.5.1) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.0.5.1) lib/active_support/callbacks.rb:101:in `run_callbacks'
actionpack (6.0.5.1) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.0.5.1) lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
appsignal (3.0.27) lib/appsignal/rack/rails_instrumentation.rb:19:in `call'
actionpack (6.0.5.1) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
actionpack (6.0.5.1) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.5.1) lib/rails/rack/logger.rb:37:in `call_app'
... [truncated]
```

Rails 6.0, puma webserver on a local development copy. I have a separate `profile` env, and load the middleware as suggested here: https://ruby-prof.github.io/#profiling-rails in `application.rb`.

I have to restart the server to get it working. Could this be something to do with middleware load order?

**Comment by NeilSlater-Clixifix** [comment]
Update: It does look like it was middleware load order. 

Using `config.middleware.insert_before 0, Rack::RubyProf, path: './profile'` in my `config/environments/profile.rb` *after* setting `config.eager_load` seems to result in a more stable setup. Very possibly the middleware could live in other places too, I'm not 100% sure what was clashing and why. But I will live with that as a quick fix, and I hope someone finds this note useful when searching that `hash.each` error message.
