### ISSUE TITLE
can we drop support for older ruby versions?

### ISSUE THREAD

**Issue by skaes** [ruby-prof/ruby-prof#230]
1.9, 2.0 and 2.1 are no longer officially supported. I think we should also no longer support them.

@rdp @schleyfox @cfis what do you think?

**Comment by rdp** [comment]
works for me.  If we introduce a "breaking" change maybe we can mention in
the README which (old) version works for "old version x" of ruby [?]

**Comment by schleyfox** [comment]
We're still on 2.1 for a fair amount of our projects, but I have no problem with dropping support.

**Comment by skaes** [comment]
@rdp I have no intent of introducing a breaking change, but as as soon as we officially drop support and disable the travis builds for those versions, breaking changes might creep in without us noticing.

**Comment by cfis** [comment]
I'm going to do a new release with various bug fixes and pull requests merged in.  Then I'll do a release that removes old ruby versions.

**Comment by cfis** [comment]
This is now done.
