### ISSUE TITLE
RubyProf.profile doesn't raise exceptions thrown inside of it

### ISSUE THREAD

**Issue by kwasimensah** [ruby-prof/ruby-prof#238]
```
RubyProf.profile { raise "hello world" }
```

This doesn't actually pass it's exception along to the context that calls it, which was super surprising and caused some debugging headaches. Might be related to profile actually living in native code. I'm using version 0.17.0.

**Comment by kwasimensah** [comment]
Also, I'm on Ruby 2.4.3

**Comment by aguynamedryan** [comment]
Seems to be related to https://github.com/ruby-prof/ruby-prof/blob/master/ext/ruby_prof/ruby_prof.c#L699 using [`rb_protect` which rescues all exceptions](https://silverhammermba.github.io/emberb/c/#rb_protect)

I'm not sure how to work around this issue.  It seems like the profiler is trying to ensure it always returns a profile result so it suppresses all exceptions.

My preference would be to have the profiler not rescue exceptions at the risk of losing my results.

**Comment by cfis** [comment]
See pull request #239.
