### ISSUE TITLE
Use END { .... } instead of at_exit { ... } in unprof.rb

### ISSUE THREAD

**Issue by zw963** [ruby-prof/ruby-prof#240]
Hi, i want to add a PR for add a new file, `lib/uby-prof.rb`, so we can use like this:

```rb
$: RUBYLIB=/MY/LIB/PATH RUBYOPT=-ruby-prof some_ruby_command
```

Add, I found, there exist a file named `lib/unprof.rb`, it almost same as my version, expect
I use this:

Editing ...

```rb
require 'ruby-prof'

END {
  result = RubyProf.stop
  printer = RubyProf::FlatPrinter.new(result)
  printer.print(STDOUT)
}
RubyProf.start
```

The difference is: 

One end block, only be register one.
But, one at_exit block, can be register any times.

**Comment by cfis** [comment]
Thanks for the idea.  The issue though is what happens if other code uses END?  The ruby profile end code may never be called.  So I think we should leave it as-is.

**Comment by zw963** [comment]
Cool, thank you.
