### ISSUE TITLE
ruby-prof 64-bit Assembler: Error In Syntax 

### ISSUE THREAD

**Issue by hitanaka156** [ruby-prof/ruby-prof#243]
Attempting to bundle install ruby-prof in a 64-bit environment causes an assembler error.

There seems to be an error in __asm__ of "./ruby-prof-0.17.0/ext/ruby_prof/rp_measure_cpu_time.c", but how to deal with bundle install ruby-prof with 64bit Should I?

OS   : AIX V7.1 TL1 SP2 (64bit)
Ruby : ruby-2.4.0-1.aix6.1 (64bit)

> ./ruby-prof-0.17.0/ext/ruby_prof/rp_measure_cpu_time.c
>   51:    `__asm__` `__volatile__` ("\n\
>   52:    1:  mftbu   %1\n\
>   53:        mftb    %L0\n\
>   54:        mftbu   %0\n\
>   55:        cmpw    %0,%1\n\
>   56:        bne-    1b"
>   57:        : "=r" (x), "=r" (y));

> /opt/freeware/bin/gcc  -maix64    -D_LARGE_FILES -O2 -I. -I/opt/freeware/include/ruby-2.4.0/powerpc-aix6.1.0.0
> -I/opt/freeware/include/ruby-2.4.0/ruby/backward -I/opt/freeware/include/ruby-2.4.0 -I. -DHAVE_RB_GC_STAT -DHAVE_RB_GC_COUNT
> -DHAVE_RB_REMOVE_EVENT_HOOK_WITH_DATA -DRUBY_PROF_RUBY_VERSION=20400     -O2 -fno-fast-math -ggdb3 -Wall -Wextra
> -Wno-unused-parameter -Wno-parentheses -Wno-long-long -Wno-missing-field-initializers -Wno-tautological-compare
> -Wno-parentheses-equality -Wno-constant-logical-operand -Wno-self-assign -Wunused-variable -Wimplicit-int -Wpointer-arith
> -Wwrite-strings -Wdeclaration-after-statement -Wimplicit-function-declaration -Wdeprecated-declarations
> -Wno-packed-bitfield-compat -Wsuggest-attribute=noreturn -Wsuggest-attribute=format -Wno-maybe-uninitialized -std=c99  -o
> rp_measure_cpu_time.o -c rp_measure_cpu_time.c
> rp_measure_cpu_time.c: In function 'measure_cpu_time':
> rp_measure_cpu_time.c:87:5: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
>      double seconds = 0;
>      ^~~~~~
> rp_measure_cpu_time.c: At top level:
> cc1: warning: unrecognized command line option '-Wno-self-assign'
> cc1: warning: unrecognized command line option '-Wno-constant-logical-operand'
> cc1: warning: unrecognized command line option '-Wno-parentheses-equality'
> Assembler:
> /tmp//cckSkhmq.s: line 144: Error In Syntax 
> /tmp//cckSkhmq.s: line 148: Error In Syntax 
> /tmp//cckSkhmq.s: line 163: Error In Syntax 
> /tmp//cckSkhmq.s: line 167: Error In Syntax 
> make: The error code from the last command is 1.
> 
> 
> Stop.
> 
> make failed, exit code 2

**Comment by hitanaka156** [comment]
gcc version is 6.3.0.
It is not ubuntu but powerpc.

> `#` gcc -v
> Using built-in specs.
> COLLECT_GCC=gcc
> COLLECT_LTO_WRAPPER=/opt/freeware/libexec/gcc/powerpc-ibm-aix7.2.0.0/6.3.0/lto-wrapper
> Target: powerpc-ibm-aix7.2.0.0
> Configured with: ../gcc-6.3.0/configure --prefix=/opt/freeware --mandir=/opt/freeware/man --infodir=/opt/freeware/info --with-local-prefix=/opt/freeware --with-as=/usr/bin/as --with-ld=/usr/bin/ld --enable-languages=c,c++,fortran,objc,obj-c++ --enable-version-specific-runtime-libs --disable-nls --enable-decimal-float=dpd --with-cloog=no --with-ppl=no --disable-libstdcxx-pch --enable-__cxa_atexit --host=powerpc-ibm-aix7.2.0.0
> Thread model: aix
> gcc version 6.3.0 (GCC)

**Comment by cfis** [comment]
Happy to take a patch if you know the correct assembly for aix.

**Comment by cfis** [comment]
This code has been removed entirely in version 1.0.0
