### ISSUE TITLE
Is the performance effect of ruby-prof proportional?

### ISSUE THREAD

**Issue by robert** [ruby-prof/ruby-prof#245]
I've used ruby-prof to hunt down the big wins in speeding up my application (thanks!), and now I'm trying to use it to hunt down the small ones.

I know that ruby-prof generally impacts a program's performance (https://github.com/ruby-prof/ruby-prof#performance). My follow-up question is:

Do the results from ruby-prof reflect a constant factor, proportional slowdown in every piece of the program? Or can the effect be different on different parts of the program?

Example:

I have 2 methods - `a_method` and `b_method`. From simple benchmarking I know that `a_method` takes 3x as long to run as `b_method`. Will this ratio be preserved in ruby-prof's output?

## Homework

I believe that this ratio will *not* always be preserved in ruby-prof's output, although often the effect will be minimal.

```ruby
require 'benchmark'
require 'ruby-prof'

def report(result)
  graph_printer = ::RubyProf::CallStackPrinter.new(result)
  graph_file_path = File.expand_path("graph-#{ts}.txt", __dir__)
  File.open(graph_file_path, "w") do |f|
    graph_printer.print(f)
  end
end

# Multiple, hierarchical `do_nothingX` methods to
# isolate the extra cost of a method call added
# by ruby-prof.
def do_nothing1(x, y)
  do_nothing2(x, y)
end

def do_nothing2(x, y)
  do_nothing3(x, y)
end

def do_nothing3(x, y)
  nil
end

# Multiple `timesX` methods to make sure ruby-prof
# doesn't fold them all into one entry.
def times1(n)
  n.times {|x| yield(x) }
end

def times2(n)
  n.times {|x| yield(x) }
end

def times3(n)
  n.times {|x| yield(x) }
end

if $0 == __FILE__
  # To make comparisons with Benchmark easier
  RubyProf.measure_mode = RubyProf::WALL_TIME

  # Benchmark with ruby-prof enabled
  result = ::RubyProf.profile do
    Benchmark.bm do |x|
      x.report { times1(10000) {|x| do_nothing1(x, x) }}
      x.report { times2(10000) {|x| do_nothing2(x, x) }}
      x.report { times3(10000) {|x| do_nothing3(x, x) }}
    end
  end
  report(result)

  # Benchmark without ruby-prof enabled
  Benchmark.bm do |x|
    x.report { 10000.times {|x| do_nothing1(x, x) }}
    x.report { 10000.times {|x| do_nothing2(x, x) }}
    x.report { 10000.times {|x| do_nothing3(x, x) }}
  end
end
```

With ruby-prof enabled:

```
   user     system      total        real
0.020000   0.010000   0.030000 (  0.026071)
0.020000   0.000000   0.020000 (  0.017250)
0.010000   0.000000   0.010000 (  0.009482)
```

Without ruby-prof enabled:

```
   user     system      total        real
0.000000   0.000000   0.000000 (  0.001443)
0.000000   0.000000   0.000000 (  0.001074)
0.000000   0.000000   0.000000 (  0.000770)
```

The ratios between the different `do_nothingX` methods are quite different when ruby-prof is enabled and when it is disabled:

```
0.026071 / 0.009482 = 2.75
0.001443 / 0.000770 = 1.87
```

This makes sense to me. Because ruby-prof adds extra cost to method calls, I assume that this non-proportional effect is most pronounced in this type of trivial program, where very little work is being done outside of jumping up and down a callstack. If we were doing intensive work inside the methods (eg calling a DB), then the non-proportional extra cost added to method calls will be a much smaller fraction of the results.

For a program where the variable, added cost of ruby-prof might distort my output, I imagine that I might be better of using a sampling profiler?

Thanks for your time and thanks for a great tool.

**Comment by rdp** [comment]
method calls are more expensive... :|

**Comment by cfis** [comment]
Could definitely give it a try and see.
