### ISSUE TITLE
what ist the unit of wall_time, process_time, cpu_time, gc_time

### ISSUE THREAD

**Issue by asoki** [ruby-prof/ruby-prof#252]
please update the documentation to make clear in what unit wall_time, process_time, cpu_time, gc_time is measured. (seconds, ms, microseconds, etc)

Thanks

**Comment by Shoroh** [comment]
And memory as well, please.

**Comment by cfis** [comment]
They are in seconds and bytes. Documentation is updated.

Thanks - Charlie
