### ISSUE TITLE
ruby-prof misreports the call stack on windows

### ISSUE THREAD

**Issue by Inversion-des** [ruby-prof/ruby-prof#256]
You can find all the delails (combination fo gems, the code to reproduce and attached reports) on this page — https://jira.mongodb.org/browse/RUBY-1831

**Comment by cfis** [comment]
Gave the test a try in ruby-prof 1.0 and it looks like it works correctly to me. So this has been fixed (a lot of work went into fixing recursive profiles).

Thanks for the report - Charlie
