### ISSUE TITLE
Is `merge_fibers` broken?

### ISSUE THREAD

**Issue by ioquatix** [ruby-prof/ruby-prof#261]
I tried using 1.0.0 and even with `merge_fibers: true` I get one report per fiber.

It works fine in 0.18.0.

Let me know how I can help fix this issue.

**Comment by cfis** [comment]
Ah - sorry - I removed it in 1.0.0 on a quest to simplify the code. I should have documented that as a change.

The way it worked was either using the fiber_id or the thread_id when collecting data - now the fiber_id is always used.

It wouldn't be a huge amount of work to put it back in, but I wasn't sure of the utility. How important is it for you?

**Comment by ioquatix** [comment]
Super important, basically makes 1.x impossible to use. Author of async here.

**Comment by cfis** [comment]
Mind expounding on that a bit? Why does it make 1.0 impossible to use?

**Comment by ioquatix** [comment]
Because I get 10,000 unmerged reports with 0.1% of the total runtime each.

**Comment by cfis** [comment]
Ah - that's a lot reports. Do you want to patch back in the old code or do you want me to?

**Comment by ioquatix** [comment]
I would love to but I am at a time deficit right now, and I don't know this code base. If you know exactly what needs to be done and can knock it out in a few hours, can you please? <3

**Comment by cfis** [comment]
See if this is fixed now, you'll need to check out the head branch to test.

**Comment by ioquatix** [comment]
Fixed.
