### ISSUE TITLE
travis builds for master are failing

### ISSUE THREAD

**Issue by skaes** [ruby-prof/ruby-prof#264]
The master build is currently failing on travis (and also on my machine). I think we should bring master to a state where travis builds are consistently passing.

https://travis-ci.org/ruby-prof/ruby-prof/builds/631386009

**Comment by cfis** [comment]
Definitely.  On my todo list. I think there is a mark error someplace. Meaning Ruby code is holding onto and accessing a ruby prof C object that was freed out from under it. If you run that test locally with enough iterations you'll see the error message.

**Comment by cfis** [comment]
Using 2.6.5 as the baseline, the test that is failing is the inverse call stack. That's a new test that tests if you start RubyProf at the bottom of a call tree.

A->B->C->D (now start RubyProf but don't end until you get back to A).

There was a test in test_basic about this, which passed on earlier versions of RubyProf but that was a bit of a mirage. Meaning the method times were correct but the call stack was wrong. 

This is corner case though, so I separate out the test from basic (its not basic) to its own test and expanded it. Current version of Ruby-prof is also broken on this. To fix requires redoing how the frames and stacks work while profiling, so a fair bit of work.

**Comment by cfis** [comment]
Ok, think I have this mostly fixed. Ruby 2.5.* and 2.6.* full pass. 2.7.* changed something with object allocation sizes and 2.4.* has a weird crash.

**Comment by cfis** [comment]
Ok, everything passes but one test on Ruby 2.4.9. I've tried to get that testing across all Ruby versions, but haven't succeeded. I think I'm going to call this good.
