### ISSUE TITLE
--exclude is broken

### ISSUE THREAD

**Issue by baelter** [ruby-prof/ruby-prof#265]
Use `--exclude` causes:

```
.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/ruby-prof-1.1.0/bin/ruby-prof:350:in `block in <top (required)>': undefined method `eliminate_methods!' for #<RubyProf::Profile:0x00007ff0a512b450> (NoMethodError)
	
```

**Comment by cfis** [comment]
Good point - thanks for bringing it up. Note method exclusion (newer) works a bit differently than method elimination (older and removed at 1.0.0). So:

--exclude="Integer#upto, Integer.superlcass"

Standard Ruby naming conventions, so:

# for instance methods
. for class methods

Note the old regex and file switches are no longer supported and have been removed.
