### ISSUE TITLE
Add max_percent and filter_by options to printers

### ISSUE THREAD

**Issue by smcgivern** [ruby-prof/ruby-prof#267]
At GitLab, we have a small custom printer, which we call TotalTimeFlatPrinter: https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/profiler/total_time_flat_printer.rb

This has two differences from the regular printers:

1. It has a `max_percent` option, to allow filtering out results over a certain threshold (to complement the existing `min_percent` option).
2. It sorts and filters by total time, not self time.

These work together: `max_percent` for self time may not be very useful, but `max_percent` by total time can filter out callers that might not be very interesting. (Imagine a web request where the call stack is large; most of the pieces at the top of that stack will have a total time of over 95%, because they are just wrappers.)

Combining the two is especially useful when hotspots aren't in Ruby code but in access to external services (like databases).

I'd like to submit a PR for this, but I thought I'd create an issue first and see if this is likely to be accepted. @cfis what do you think of this proposal?

**Comment by cfis** [comment]
Sounds good to me!
