### ISSUE TITLE
Odd call stack nesting in Ruby 2.7.0 and 2.7.1

### ISSUE THREAD

**Issue by MacksMind** [ruby-prof/ruby-prof#279]
In the code below, I didn't expect a big change between Ruby 2.6.6 and 2.7.1. In practice, calling `100.times { SecureRandom.gen_random(10) }` doesn't change, but calling `100.times { SecureRandom.uuid }` changes dramatically.

``` ruby
#!/usr/bin/env ruby

require 'bundler/inline'
require 'securerandom'

gemfile do
  source 'https://rubygems.org'
  gem 'ruby-prof', git: 'https://github.com/ruby-prof/ruby-prof'
end

uuid = RubyProf::Profile.new
uuid.exclude_methods!(Integer, :times)
uuid.start
100.times { SecureRandom.uuid }
uuid.stop

File.open('uuid.html', 'w') do |f|
  RubyProf::CallStackPrinter.new(uuid).print(f)
end

gen_random = RubyProf::Profile.new
gen_random.exclude_methods!(Integer, :times)
gen_random.start
100.times { SecureRandom.gen_random(10) }
gen_random.stop

File.open('gen_random.html', 'w') do |f|
  RubyProf::CallStackPrinter.new(gen_random).print(f)
end
```

**Comment by cfis** [comment]
Can you attach the results you are seeing? What's different?

**Comment by MacksMind** [comment]
It won't let me upload the html, but here's a screenshot with Ruby 2.6.6 on the left, and 2.7.1 on the right.

<img width="2560" alt="Screen Shot 2020-09-02 at 7 12 31 AM" src="https://user-images.githubusercontent.com/17553/91974436-c6807b00-eceb-11ea-9c51-ae0fcb8430ce.png">

**Comment by cfis** [comment]
Ah. Yeah that doesn't look good. Not sure what would have changed with Ruby 2.7.1 but will take a look.

**Comment by cfis** [comment]
Ok, this is a ruby bug. See https://bugs.ruby-lang.org/issues/17152.

**Comment by MacksMind** [comment]
Looks like the fix from 3.0 got backported to the 2.7.x trunk. Leave this open for reference until 2.7.2 ships, or ???

**Comment by cfis** [comment]
I'll update the docs to note this, and then close this ticket. Had a similar problem in an older version of Ruby. Thanks for finding this!

**Comment by MacksMind** [comment]
Verified that Ruby 2.7.2 resolves the issue.

**Comment by cfis** [comment]
Thanks!

https://github.com/ruby-prof/ruby-prof.github.io/commit/de57d29108c6e498f5872319951920ed63016234
