### ISSUE TITLE
Profile.new ignores measure_mode

### ISSUE THREAD

**Issue by paddor** [ruby-prof/ruby-prof#281]
Hi

I create one of the profiles like this:

```ruby
profile = RubyProf::Profile.new measure_mode: RubyProf::PROCESS_TIME, merge_fibers: true
# ...
profile.stop
printer = RubyProf::FlatPrinter.new profile
File.open('profile.flat', 'w') { |file| printer.print file }
```

I expect the file to start with `Measure Mode: process_time`, but it starts with `Measure Mode: wall_time`.
If I set `RubyProf.measure_mode = RubyProf::PROCESS_TIME`, it works as expected.

I'm on Ruby 2.7.1 and RubyProf 1.4.1

**Comment by cfis** [comment]
The results were correct, but the label was incorrect. Fixed.
Thanks for the report.
