### ISSUE TITLE
Incorrect call stack nesting in Ruby 2.7.2

### ISSUE THREAD

**Issue by AlexMooney** [ruby-prof/ruby-prof#282]
This is a similar issue to #279, but with the Redis gem instead of SecureRandom.  I tried `SecureRandom.uuid` and a few other permutations in place of `Redis.current.set`, but I couldn't find any other methods that reproduce the problem.

```ruby
require 'Redis'
require 'ruby-prof'

Widget = Struct.new(:key) do
  def set!
    Redis.current.set(key, 1, ex: 10)
  end
end

result = RubyProf.profile do
  (1..20).each { |i| Widget.new(i).set! }
end

printer = RubyProf::CallStackPrinter.new(result)
File.open("framez.html", 'w:ASCII-8BIT') do |file|
  printer.print(file, {})
end
```

[framez.html.gz](https://github.com/ruby-prof/ruby-prof/files/5484539/framez.html.gz)

![image](https://user-images.githubusercontent.com/8269566/98048787-46f25380-1de3-11eb-90cb-e28a8f12d185.png)

**Comment by cfis** [comment]
Are you sure you are using Ruby 2.7.2? Looks fine to me here:

![image](https://user-images.githubusercontent.com/18630/98062437-e07d2d80-1e02-11eb-930d-b959ece51dc9.png)

**Comment by AlexMooney** [comment]
I just made the file fresh from my comment and it still looks the same.  I'm using rbenv to set the Ruby version and it seems correct to me:

```bash
$ ruby --version
ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-darwin19]
```

Also I see "2.7.2" when I add `puts RUBY_VERSION` to the script.

**Comment by cfis** [comment]
Sorry to miss your response. I can't duplicate this either on MacOS or Windows. So not sure how to proceed. I checked Ruby 2.7.2 and Ruby 3.0.

**Comment by AlexMooney** [comment]
I've recreated the file and run it again with 2.7.2 and it seems like the bug is gone.  Must have been a weird version of the Redis gem, or some sort of gremlin in my old setup.  Or just plain old user error.  😆  Thanks for looking @cfis!

![image](https://user-images.githubusercontent.com/8269566/107264728-32cc7c80-69f8-11eb-9b7f-9a853ca4deb9.png)

**Comment by cfis** [comment]
That's good to hear! Thanks for checking.
