### ISSUE TITLE
Greatly increased binary size on Windows?

### ISSUE THREAD

**Issue by thomthom** [ruby-prof/ruby-prof#294]
I noticed that the `.so` filesize for the earlier versions 0.15 - 0.17 ranged from ~35KB to 65KB. Clearly lost of things have changed recently (thank you for all the work!). But on my system the binary for 1.4.2 is now ~17,4 MB.

Any idea why the size has grown that much?

Background for this is that I maintain a Ruby API exposed within an application that embeds Ruby. In this case the embedded Ruby isn't able to make sure of the gems automatically building the C binaries, so I've been pre-compiling them. This is why I noticed the file size increase.

The binary on my machine is a result of calling `gem install ruby-prof` from a standalone installation of Ruby 2.7. Not from building from the repository source directly.

**Comment by cfis** [comment]
I'd guess its due to debug symbols...would have to look.

**Comment by thomthom** [comment]
Are they getting embedded into the binary? I didn't even know that was possible with Windows binaries. Anything I can do to assist?

**Comment by cfis** [comment]
The library is built with gcc on windows. Size is 17MB. Then run:

```bash
 strip --strip-all ruby_prof.so
```

It becomes 78k. So quite a difference.

**Comment by thomthom** [comment]
Wow - didn't realize symbols for an otherwise small binary could get that big. Thank you for the fix! 👍👍
