### ISSUE TITLE
CallStackPrinter now display everything in bold

### ISSUE THREAD

**Issue by thomthom** [ruby-prof/ruby-prof#297]
Before it used to look like the example linked in the docs: https://ruby-prof.github.io/examples/primes.stack.html

https://ruby-prof.github.io/examples/primes.stack.html
![image](https://user-images.githubusercontent.com/192418/107060502-55337f80-67d7-11eb-82df-0c3ff0ff90d1.png)

What I'm seeing with 1.4.2 is that almost all text is now bold:

![image](https://user-images.githubusercontent.com/192418/107060420-3b923800-67d7-11eb-99ff-2ad66cf49d65.png)

I find this harder to read. (Already found it hard to read with a serif font at such a small size.)

Would be nice to have the text appear with less box and with a simpler sans-serif font.

Btw, would it be of interest if I tried to tweak this reporter a bit?

- Not all bold text.
- Sans serif font
- Reduce the border of each element, making it more flat for reduced visual noise.

I wouldn't want to make any other radical changes. This reporter is very compact, but given how much data it displays I think that's appropriate.

**Comment by cfis** [comment]
Sure, sounds good.

**Comment by cfis** [comment]
Any progress?

**Comment by thomthom** [comment]
Sorry, no. I've gotten an inflammation in my arm so I've been using the computer at absolute minimum this last week.

**Comment by cfis** [comment]
I changed the text to normal weight. If you'd like to update the format more, please open a new ticket.
