### ISSUE TITLE
Doc link to callgrind example yields 404

### ISSUE THREAD

**Issue by thomthom** [ruby-prof/ruby-prof#298]
While going through the docs (https://ruby-prof.github.io/#reports) I found a dead link:

![image](https://user-images.githubusercontent.com/192418/107061095-0b976480-67d8-11eb-9445-053d4f7ff4f3.png)

Links to https://ruby-prof.github.io/examples/primes.callgrind.out.2540

**Comment by cfis** [comment]
Thanks and fixed.
