### ISSUE TITLE
UniqueCallPathTest#test_root_children fails in i386 architecture agianst ruby 2.7.3

### ISSUE THREAD

**Issue by utkarsh2102** [ruby-prof/ruby-prof#302]
Hello,

Thanks for working on this! 😄 

However, whilst building `ruby-prof` against ruby 2.7.3 in i386 architecture, the `UniqueCallPathTest#test_root_children` failed :(
Here's the diff:
```
  1) Failure:
UniqueCallPathTest#test_root_children [/tmp/autopkgtest-lxc.79b0z70i/downtmp/build.qSd/src/test/unique_call_path_test.rb:56]:
--- expected
+++ actual
@@ -1 +1 @@
-"UniqueCallPath#method_k"
+"UniqueCallPathTest#test_root_children"
```

The same test passes on amd64, arm64, and ppc64el. Thus I am a bit puzzled. Do you happen to know the cause or something?

**Comment by cfis** [comment]
Sorry - no idea. Weird the profile is starting at one higher level.

Since I don't have a machine with the i386 architecture, I'm going to close this.

**Comment by utkarsh2102** [comment]
I really don't think this should be marked as "completed". It's an actual issue on the i386 architecture. Perhaps declare that architecture as unsupported?

**Comment by cfis** [comment]
Happy to take a patch if you have time to figure out the issue.
