### ISSUE TITLE
Rubydoc minimum version conflicts with actual minimum version

### ISSUE THREAD

**Issue by l4cr0ss** [ruby-prof/ruby-prof#303]
Rubydoc states that the minimum required ruby version is 2.4.0, but attempting to install on v2.4.6 results in the following error:

```
$ gem install ruby-prof
Fetching: ruby-prof-1.4.3.gem (100%)
ERROR:  Error installing ruby-prof:
	ruby-prof requires Ruby version >= 2.5.0.
```

**Comment by l4cr0ss** [comment]
```
$ rbenv version
2.4.6
```

**Comment by l4cr0ss** [comment]
![image](https://user-images.githubusercontent.com/3689038/135891713-2c7bfccd-d7ce-4d38-affb-29a22b1a4756.png)

**Comment by cfis** [comment]
Thanks - fixed.
