### ISSUE TITLE
Some items have nonsensical (very large) total time

### ISSUE THREAD

**Issue by ujetjeremy** [ruby-prof/ruby-prof#305]
It's entirely possible I've misunderstood the output here, but I've looked through all the documentation and I can't seem to find an answer.

When I take time profiles and print the output with `GraphHtmlPrinter` I see a number of cases where the total time for child or parent items well exceed the total time of the current item or really the entire profiling session.  Here's an example:

![Screen Shot 2022-01-18 at 5 52 27 PM](https://user-images.githubusercontent.com/62615873/150037476-359a8db6-286c-4db5-a95c-4e40188f3115.png)

In this case, the profiler ran for a few minutes so I think the "205.62 seconds" for total time is right.  I have no clue where the "64104.11" or "62779.33" or "1324.76" are coming from.  If you click any of those children / parent items, their bolded line correctly shows "205.62" or something close to it.  I'm not sure why they're different.

Originally I thought these might aggregate if a method is called recursively or something, but I can find cases in my profile where that doesn't seem to happen, so it seems like maybe this is just a bug.

**Comment by cfis** [comment]
Can you share the code that produced this output?

**Comment by cfis** [comment]
Closing since haven't heard back. Happy to look if you can provide the code that was profiled.
