### ISSUE TITLE
deprecated RubyProf replacments

### ISSUE THREAD

**Issue by johrstrom** [ruby-prof/ruby-prof#306]
Hi, [rails-perftest](https://github.com/rails/rails-perftest) is using deprecated methods that were pulled in this commit. 

https://github.com/ruby-prof/ruby-prof/commit/e39b571000dae9140a2790dd399b5f76113eca5f

I just have the small question that libraries that were using 
```ruby
RubyProf.measure_wall_time
```

Can simply replace that call with?
```ruby
Measure::ProcessTime.measure
```

I'm not super familiar with either code bases but am trying to get it to work with my rails app and would just like to know if I can drop-in replace the 2 method calls with gem `1.4.3`.

**Comment by johrstrom** [comment]
Sorry for the noise - I think I found what I'm looking for https://github.com/beansmile/rails-perftest/commit/bdb96c5c2b9def313cba369c96342350ce10ade8

**Comment by cfis** [comment]
Ok cool. That looks good to me.
