### ISSUE TITLE
Flaky test suite

### ISSUE THREAD

**Issue by Lewiscowles1986** [ruby-prof/ruby-prof#311]
https://github.com/Lewiscowles1986/ruby-prof/runs/6994595317?check_suite_focus=true more directly links the last passing branch from Travis, even omitting osx and windows (for-now, it's still in a matrix).

Even with that branch the CI (possibly the test-suite itself) sometimes fails, but upon re-run does not.

Seeds

* [X] 1658
* [X] 63686
* [X] 2621
* [X] 26549

Cause of failures is unknown...

**Comment by cfis** [comment]
Yeah some tests, especially on windows, are sometimes off by a little bit.

**Comment by Lewiscowles1986** [comment]
@cfis this seems to be affecting all the operating systems. The failures linked are all Linux.

What I Can't work out for the life of me is how the numbers could be wrong, or if perhaps the tests giving an absolute time, might cause more problems than they solve.

**Comment by cfis** [comment]
Some tests measure process time and some measure wall time. I have spent a fair bit of time over the years to try and not have flaky test suite, but haven't really succeeded. Going to close since I'm not sure there is a fix.

**Comment by Lewiscowles1986** [comment]
I Really feel like this should be open with `cantfix` or `wontfix`; at the very least it should be an indicator that this cannot really be relied upon.
