### ISSUE TITLE
There is no way to remove the base_name when generate callgrind.out use CallTreePrinter

### ISSUE THREAD

**Issue by zw963** [ruby-prof/ruby-prof#313]
For now, when i use CallTreePrinter, it generate a file like this: `profile.callgrind.out.356507`.

But the unfortunately thing is, when open KCachegrind in linux, it could not find it.

Following [this](https://stackoverflow.com/a/31615112/749774) answer in SO, after change `profile.callgrind.out.356507` to `callgrind.out.356507`,  KCachegrind can find the file now.

How to avoid the `profile.` part of generated file? there is no way.

https://github.com/ruby-prof/ruby-prof/blob/master/lib/ruby-prof/printers/call_tree_printer.rb#L104

when i pass profile as nil, `printer.print(profile: nil)`, this will generate a hide file, `.callgrind.out.356507`.

So, how to generate a file prefix with callgrind, like `callgrind.out.356507`?

**Comment by cfis** [comment]
Hmm, sounds like the code needs to be patched. But is this a change in KCacheGrind, it used to work fine?

**Comment by zw963** [comment]
> it used to work fine?

Probably no.

**Comment by cfis** [comment]
It did since I have used it in the past. But that was quite a few years ago.

**Comment by cfis** [comment]
So this does work. When you open KCacheGrind, in the bottom right of the open file dialog is a button that let's  you select "All Files." Select that, then you can open the profile results.

However it is true that KCacheGrind by default looks for files that start with `callgrind` or 'cachegrind` - see:

https://github.com/KDE/kcachegrind/blob/d4f2e55c712453e326d47fa40c140ffae267769a/qcachegrind/qcgtoplevel.cpp#L851

So I went ahead and removed the profile option that lets you set the prefix.
