### ISSUE TITLE
Ruby 3.2.0 support

### ISSUE THREAD

**Issue by kapso** [ruby-prof/ruby-prof#317]
rails aborted!
LoadError: cannot load such file -- /Users/kapil/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/ruby-prof-1.4.4/ext/ruby_prof/ruby_prof.so

- Re-installed the gem, but did not fix the issue
- Removed the gem from Gemfile, and that fixed the issue

**Comment by rdp** [comment]
Does that file exist?

**Comment by cfis** [comment]
@kapso we will need more information than you have provided to help.  I cannot reproduce this.

```
gem install ruby-prof 
Fetching ruby-prof-1.4.4.gem
Building native extensions. This could take a while...
Successfully installed ruby-prof-1.4.4
Parsing documentation for ruby-prof-1.4.4
Installing ri documentation for ruby-prof-1.4.4
Done installing documentation for ruby-prof after 0 seconds
1 gem installed
```

Notice the message about building native extensions. Do you see that? Note this is with Ruby 3.1.3 installed via brew.

Then:

```
ll /usr/local/lib/ruby/gems/3.1.0/gems/ruby-prof-1.4.4/ext/ruby_prof/ruby_prof.bundle
-rwxr-xr-x  1 csavage  admin  78448 Dec 26 23:30 /usr/local/lib/ruby/gems/3.1.0/gems/ruby-prof-1.4.4/ext/ruby_prof/ruby_prof.bundle
```

**Comment by kamilpogo** [comment]
I have the same problem after upgrading to ruby 3.2.0
Installation looks good:
```
$ gem install ruby-prof
Fetching ruby-prof-1.4.4.gem
Building native extensions. This could take a while...
Successfully installed ruby-prof-1.4.4
Parsing documentation for ruby-prof-1.4.4
Installing ri documentation for ruby-prof-1.4.4
Done installing documentation for ruby-prof after 0 seconds
1 gem installed
```
ruby_prof.so exists in /.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/ruby-prof-1.4.4/lib but not in /.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/ruby-prof-1.4.4/ext/ruby_prof (which is where the source is located)

Changing line 9 of ruby-prof.rb from
```
  require_relative "../ext/ruby_prof/ruby_prof.so"
```
to
```
  require_relative "ruby_prof.so"
```
fixes the problem

**Comment by cfis** [comment]
Ok, the code of interest:

`begin
  version = Gem::Version.new(RUBY_VERSION)
  require "#{version.segments[0..1].join('.')}/ruby_prof.so"
rescue LoadError
  require_relative "../ext/ruby_prof/ruby_prof.so"
end`

The real problem is on install ruby_prof.so is now getting put in the lib directory and not lib/3.2 like it should be. That's some change in Ruby 3.2 it looks.

**Comment by kamilpogo** [comment]
Maybe the problem is in the rakefile in line 30
`ext.lib_dir = "lib/#{Gem::Version.new(RUBY_VERSION).segments[0..1].join('.')}"`

**Comment by cfis** [comment]
Well that hasn't changed in quite a while and is supposed to separate out 3.0, 3.1, 3.2, etc. But it does look like Ruby 3.2 is breaking that. Anyway, worth a try to change it and see what happens.

**Comment by cfis** [comment]
FYI, rake compile or rake native gem works fine on 3.2 (as they should).
