### ISSUE TITLE
Bump ruby-prof from 1.5.0 to 1.6.0 is failing

### ISSUE THREAD

**Issue by kapso** [ruby-prof/ruby-prof#318]
```
rails db:migrate
rails aborted!
LoadError: cannot load such file -- /Users/kapil/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/ruby-prof-1.6.0/ext/ruby_prof/ruby_prof.so
```

**Comment by cfis** [comment]
So where is ruby_prof.so then (well on MacOS ruby_prof.bundle)? In ruby_prof/lib?

What does `ruby -v` return? How did you install the gem?

A clean install on Linux works fine. And at least on the github ci/cd a clean install also works fine on MacOS.

**Comment by cfis** [comment]
Ok 1.6.1 should work, just tested on MacOS. Thanks for the report.

**Comment by tonobo** [comment]
Hey, any reasons why you have yanked the 1.6.0. It will break bundled applications.

**Comment by cfis** [comment]
Because it didn't work on MacOS.
