### ISSUE TITLE
Documentation for 'Wait' column in case of memory profile report

### ISSUE THREAD

**Issue by surenderk2009** [ruby-prof/ruby-prof#322]
I understand the wait column in case of a time based report. I do not see much detail in documentation about the 'Wait' column in case of memory profiling. What does the wait memory signify? 

%Total 	%Self 	Total 	                 Self 	Wait 	                Child 	        Calls 	Name 	Allocations 	Line
100.00% 	0.00% 	16113083896.00 	120.00 	16045997336.00 	67086440.00 	503

**Comment by cfis** [comment]
Hah that is a good question. It would mean the same thing as with time. x number of seconds passed with the thread is waiting. So for memory profiling in your example, while the thread was waiting 16045997336.00  bytes of memory was allocated by other threads.

**Comment by surenderk2009** [comment]
The system for which I was generating the report appears to spawn a lot of things in parallel so matching the numbers looks difficult for this one. I'll test it using a small example and see if the values match but I get the idea. Let me see. Thanks. Closing the issue for now.
