### ISSUE TITLE
Issue with setting measure_mode in RubyProf

### ISSUE THREAD

**Issue by jairosoto05** [ruby-prof/ruby-prof#332]
### Description of the problem:

I’m trying to set the value of `measure_mode` in `RubyProf`, but I’m encountering two different issues:

**Using `RubyProf.measure_mode`:**
When I try to set `RubyProf.measure_mode = RubyProf::PROCESS_TIME`, I get the following warning:
> NOTE: RubyProf.measure_mode= is deprecated; use RubyProf::Profile#measure_mode= instead.

**Using `RubyProf::Profile#measure_mode`:**
I tried to follow the warning and use the recommended method, `RubyProf::Profile#measure_mode=`, but I get the following error:
> undefined method `measure_mode=' for class RubyProf::Profile (NoMethodError)

**Example code:**

```ruby
# Attempt 1: Using RubyProf.measure_mode (deprecated)
RubyProf.measure_mode = RubyProf::PROCESS_TIME

# Attempt 2: Using RubyProf::Profile#measure_mode (results in error)
profile = RubyProf::Profile.new
profile.measure_mode = RubyProf::PROCESS_TIME  # NoMethodError
```
I know there's another way to set measure_mode by using the following pattern:
```ruby
result = RubyProf::Profile.profile(measure_mode: RubyProf::ALLOCATIONS) do
  # ... code to profile ...
end
```
But I would like to know if the method will still be available in the future, or if it will be completely replaced by this block syntax.

**Environment:**

RubyProf version: 1.7.1
Ruby version: 3.3.6

**Comment by cfis** [comment]
Yes, that would be great!
