### ISSUE TITLE
Profiling with RubyProf::ALLOCATIONS does not show results unless track_allocations: true is used

### ISSUE THREAD

**Issue by jairosoto05** [ruby-prof/ruby-prof#336]
When using `RubyProf::Profile.new(measure_mode: RubyProf::ALLOCATIONS)`, all the profiling results are 0 unless the `track_allocations: true` option is explicitly set.

Is `track_allocations: true` required for accurate results when measuring ALLOCATIONS? Or is there another configuration needed to track allocations without setting this flag?

### Example code:

```ruby
require 'date'
require 'ruby-prof'

profile = RubyProf::Profile.new(measure_mode: RubyProf::ALLOCATIONS)

profile.start
Date.parse("2024-11-21")
result = profile.stop

printer = RubyProf::FlatPrinter.new(result)
printer.print(File.open("example_FlatPrinter.txt", "w+"))
```
### Result:
``` text
Measure Mode: allocations
Thread ID: 80
Fiber ID: 60
Total: 0.000000
Sort by: self_time

 %self      total      self      wait     child     calls  name                           location
   NaN      0.000     0.000     0.000     0.000        1   Integer#div                    
   NaN      0.000     0.000     0.000     0.000        1   String#[]=                     
   NaN      0.000     0.000     0.000     0.000        1   MatchData#end                  
   NaN      0.000     0.000     0.000     0.000        1   MatchData#begin                
   NaN      0.000     0.000     0.000     0.000        2   Regexp#match                   
   NaN      0.000     0.000     0.000     0.000        1   String#gsub!                   
   NaN      0.000     0.000     0.000     0.000        1   <Class::Date>#parse            
   NaN      0.000     0.000     0.000     0.000        1   [global]#                      ./example.rb:7
```

### Environment:

RubyProf version: 1.7.1
Ruby version: 3.3.6

**Comment by cfis** [comment]
Yes, I agree that is suprising. When profiling memory, we force track_allocations on. See:

https://github.com/ruby-prof/ruby-prof/blob/master/ext/ruby_prof/rp_measure_memory.c#L37

But when profiling allocations we don't:

https://github.com/ruby-prof/ruby-prof/blob/master/ext/ruby_prof/rp_measure_allocations.c#L36

That line should be changed to true.
