### ISSUE TITLE
Memory / Allocations profiling NaN in 1.9.3

### ISSUE THREAD

**Issue by zbskii** [ruby-prof/ruby-prof#86]
Running some test code like:
https://gist.github.com/3699880

Returns a profile:

```
Thread ID: 15769580
Total: 0.000000
Sort by: self_time

 %self     total     self     wait    child    calls   name
   NaN      0.00     0.00     0.00     0.00  1000000   Array#initialize 
   NaN      0.00     0.00     0.00     0.00  1000000   <Class::Array>#allocate 
   NaN      0.00     0.00     0.00     0.00  1000000   Class#new 
   NaN      0.00     0.00     0.00     0.00        1   Integer#times 
   NaN      0.00     0.00     0.00     0.00        1   Global#[No method] 
```

**Comment by fmnoise** [comment]
Still having this issue with ruby 2.1.2 and ruby-prof 0.14.2

**Comment by ziyan-junaideen** [comment]
Issues with Ruby 2.3.0

**Comment by bastengao** [comment]
Same issue ruby-prof (0.16.2) on ruby 2.2.3

**Comment by rdp** [comment]
2.3.1?

**Comment by alexbel** [comment]
@rdp yes. ruby 2.3.1p112

**Comment by fernandobrito** [comment]
For me running the test code by the original poster works fine with 2.3.3 installed using ```rvm install 2.3.3-railsexpress --patch railsexpress``` and with ruby-prof 0.16.2.

However, when running on my Ruby on Rails project (4.2.7.1), I get NaN and 0's, just like the original poster. I will try with an empty project.

**Comment by art-solopov** [comment]
I'm having the same problem as @fernandobrito. Measuring MEMORY in a plain file works well, but measuring it in a Rails project produces NaNs.
